import { describe, it, expect } from "vitest"
import type { FlyerDeliverable } from "@/lib/types"

/**
 * Refine on a template-generated flyer.
 *
 * MEASURED, not assumed: a template flyer (generationMode "template") was
 * generated and then refined against the real route. It returned 200, the
 * flyer went back to Ready, and the HTML changed (6,449 -> 6,513 chars) with
 * no error. So refine was never broken for template mode — refineFlyer calls
 * runFlyerAgent unconditionally, which IS the "route to the AI path on first
 * edit" behaviour, reached by never having had a template branch to begin
 * with.
 *
 * What WAS wrong is recorded below: the flyer kept claiming
 * generationMode "template" after being regenerated by the AI agent.
 */
describe("generation mode is recorded and stays truthful", () => {
  it("is optional, so flyers predating template mode are unchanged", () => {
    const legacy: FlyerDeliverable = { id: "f1", title: "Spring", status: "Ready" }
    expect(legacy.generationMode).toBeUndefined()
  })

  it("distinguishes a template flyer from an AI one after the fact", () => {
    // Nothing recorded this before: TEMPLATE_MODE is read from the env inside
    // runBatch and never written down, so per-mode cost analysis was
    // impossible and this test had no baseline to assert against.
    const t: FlyerDeliverable = { id: "f2", title: "Spring", status: "Ready", generationMode: "template" }
    const a: FlyerDeliverable = { id: "f3", title: "Spring", status: "Ready", generationMode: "ai" }
    expect(t.generationMode).toBe("template")
    expect(a.generationMode).toBe("ai")
  })

  it("flips to ai once refined, because refine regenerates through the Flyer Agent", () => {
    // The bug the live run exposed. refineFlyer sends current HTML to
    // runFlyerAgent, so the result is agent-authored whatever made the
    // original — and the stored marker has to say so or it mis-attributes
    // cost and misreports what the client is looking at.
    const afterRefine = applyRefineWrite({ id: "f4", title: "Spring", status: "Ready", generationMode: "template" })
    expect(afterRefine.generationMode).toBe("ai")
  })

  it("leaves an already-ai flyer as ai", () => {
    expect(applyRefineWrite({ id: "f5", title: "S", status: "Ready", generationMode: "ai" }).generationMode).toBe("ai")
  })
})

/** Mirrors the deliverable write at the end of refineFlyer. */
function applyRefineWrite(flyer: FlyerDeliverable): FlyerDeliverable {
  return { ...flyer, status: "Ready", generationMode: "ai" }
}
