// ---------------------------------------------------------------------------
// OneFlyer shared data contracts
//
// These interfaces define the shapes exchanged between the marketing site,
// the client dashboard, and the EXTERNAL Claude-based agent pipeline (built
// outside of v0). Keep them stable so the pipeline can match up cleanly.
// ---------------------------------------------------------------------------

// "free" | "pro" is shared between the marketing pricing tier a visitor
// picks AND the real enforcement flag on a client's persisted record — see
// ClientRecord below. They are NOT the same authority: a client's real
// enforcement plan only ever changes via the admin route
// (POST /api/admin/set-plan). Submitting an intake with planId "pro" never
// grants pro status by itself — there's no billing wired up yet, so trusting
// the client-selected planId for enforcement would let anyone bypass the
// free-tier limit just by editing the URL.
export type PlanId = "free" | "pro"

export interface Plan {
  id: PlanId
  name: string
  /** Short punchy positioning line under the name */
  tagline: string
  /** Small badge shown on the card, e.g. "Most Popular" */
  badge?: string
  /** Recurring monthly fee in whole dollars. 0 for the free tier. */
  monthlyFee: number
  description: string
  features: string[]
  /** A short callout reinforcing what this tier is for */
  note: string
  /** A short outcome-focused line reinforcing the result they get */
  outcome: string
  mostPopular?: boolean
  /** Placeholder Stripe price ID — wire this to a real price later. Unused for the free tier. */
  stripeMonthlyPriceId?: string
  ctaLabel: string
  /**
   * If set, the CTA renders as a plain link to this href instead of
   * triggering onSubscribe — for a tier with no real self-serve checkout
   * yet (e.g. a mailto: contact link). A button whose label promises an
   * upgrade but silently does nothing is worse than an honest "contact us."
   */
  ctaHref?: string
}

/** Shared reassurance line shown beneath both plans */
export const PLAN_GUARANTEE = "Cancel anytime · You own every flyer you generate"

/** Lifetime flyer limit for the free tier — must match the real enforcement in lib/store.ts */
export const FREE_FLYER_LIMIT = 20

/** Explains how the two tiers relate, shown beneath the pricing grid */
export const PLAN_EXPLAINER =
  `Every flyer is generated by our AI design engine and automatically brand-matched to your business — colors, fonts, and layout, no design skills required. Free includes ${FREE_FLYER_LIMIT} flyers to try it out; Pro removes the limit entirely.`

// ---- Intake / onboarding -------------------------------------------------

export type BrandStyle = "modern" | "classic" | "playful" | "minimal"

export interface ServiceItem {
  id: string
  name: string
}

export interface IntakeSubmission {
  planId: PlanId | null
  businessName: string
  industry: string
  yearsInBusiness: string
  services: ServiceItem[]
  logoFileName?: string
  brandColors?: string
  preferredStyle: BrandStyle
  voiceTone: string
  targetAudience: string
  contact: {
    email: string
    phone: string
    address: string
    website: string
    socialHandles: string
  }
  existingMaterialsFileName?: string
  flyerNotes: string
  websitePreferences: string
  submittedAt?: string
}

// ---- Client records (usage limits) ---------------------------------------

// Persisted per-email record used for real enforcement of the free-tier
// flyer limit. plan here is authoritative and only changes via the admin
// route — never inferred from an IntakeSubmission's planId.
export interface ClientRecord {
  email: string
  plan: PlanId
  /** Lifetime count — never resets. Incremented before the flyers it counts are generated. */
  flyersCreated: number
}

// ---- Deliverables / dashboard --------------------------------------------

export type FlyerStatus = "Pending" | "In Progress" | "Ready" | "Failed"
export type IntakeStatus = "Submitted" | "Not started"
export type BillingStatus = "Active" | "Past due" | "Trialing"

export interface FlyerDeliverable {
  id: string
  title: string
  status: FlyerStatus
  thumbnailUrl?: string
  downloadUrl?: string
  /** Set when status is "Failed" — shown to the client, with a retry option. */
  error?: string
}

export interface Deliverables {
  planId: PlanId
  planName: string
  billingStatus: BillingStatus
  intakeStatus: IntakeStatus
  flyers: FlyerDeliverable[]
  /** The latest submitter's real usage, for the dashboard's usage indicator. Null email = no intake yet. */
  email: string | null
  flyersCreated: number
  /** null = unlimited (pro tier) */
  flyersLimit: number | null
}
