// ---------------------------------------------------------------------------
// OneFlyer shared data contracts
//
// These interfaces define the shapes exchanged between the marketing site,
// the client dashboard, and the EXTERNAL Claude-based agent pipeline (built
// outside of v0). Keep them stable so the pipeline can match up cleanly.
// ---------------------------------------------------------------------------

// The three real tiers — used BOTH for the marketing pricing page a visitor
// picks from AND as the real enforcement flag on a client's persisted
// record (see ClientRecord below). Picking a tier on the marketing page
// (via the onboarding ?plan= query string) is only ever a REQUEST — it does
// NOT by itself grant that plan. A client's real enforcement plan only ever
// changes via the admin route (POST /api/admin/set-plan), never inferred
// from an IntakeSubmission's planId — there's no real Stripe billing wired
// up yet, so trusting a client-selected value for enforcement would let
// anyone grant themselves Basic/Pro just by editing the URL.
export type PlanId = "trial" | "basic" | "pro"

// Real per-plan flyer caps — the single source of truth for both real
// enforcement (lib/store.ts, app/api/intake/route.ts) and marketing copy
// (lib/plans.ts), so the two can't drift out of sync the way the old
// marketing numbers did before this existed.
//
// These reset every 30 days from each client's own tracked period start
// (see ClientRecord.periodStart) — a real, enforced rolling window, not
// just a display label. Anchored to our own clock rather than a Stripe
// billing period since no real Stripe subscription exists yet; once it
// does, periodStart can be re-anchored to Stripe's current_period_start.
export const PLAN_LIMITS: Record<PlanId, number> = {
  trial: 3,
  basic: 15,
  pro: 25,
}

export interface Plan {
  id: PlanId
  name: string
  /** Short punchy positioning line under the name */
  tagline: string
  /** Small badge shown on the card, e.g. "Most Popular" */
  badge?: string
  /** Recurring monthly fee in whole dollars. 0 for the free trial tier. */
  monthlyFee: number
  description: string
  features: string[]
  /** A short callout reinforcing what this tier is for */
  note: string
  /** A short outcome-focused line reinforcing the result they get */
  outcome: string
  mostPopular?: boolean
  /** Placeholder Stripe price ID — wire this to a real price once a Stripe account exists. Unused for the free trial tier. */
  stripeMonthlyPriceId?: string
  ctaLabel: string
  /**
   * If set, the CTA renders as a plain link to this href instead of
   * triggering onSubscribe — for a tier with no real self-serve checkout
   * yet (e.g. a mailto: contact link). A button whose label promises an
   * upgrade but silently does nothing is worse than an honest "contact us."
   * Unused for all three current tiers — every button routes to onboarding.
   */
  ctaHref?: string
}

/** Shared reassurance line shown beneath all plans */
export const PLAN_GUARANTEE = "Cancel anytime · You own every flyer you generate"

/** Explains how the three tiers relate, shown beneath the pricing grid */
export const PLAN_EXPLAINER =
  "Every flyer is generated by our AI design engine and automatically brand-matched to your business — colors, fonts, and layout, no design skills required. Start with a free trial, then choose Basic or Pro as your business grows."

// ---- Intake / onboarding -------------------------------------------------

export type BrandStyle = "modern" | "classic" | "playful" | "minimal"

export interface ServiceItem {
  id: string
  name: string
}

export interface IntakeSubmission {
  planId: PlanId | null
  businessName: string
  industry: string
  yearsInBusiness: string
  services: ServiceItem[]
  logoFileName?: string
  brandColors?: string
  preferredStyle: BrandStyle
  voiceTone: string
  targetAudience: string
  contact: {
    email: string
    phone: string
    address: string
    website: string
    socialHandles: string
  }
  existingMaterialsFileName?: string
  flyerNotes: string
  websitePreferences: string
  submittedAt?: string
}

// ---- Client records (usage limits) ---------------------------------------

// Persisted per-email record used for real enforcement of each plan's
// flyer limit (see PLAN_LIMITS). plan here is authoritative and only
// changes via the admin route — never inferred from an IntakeSubmission's
// planId (see the note on PlanId above).
export interface ClientRecord {
  email: string
  plan: PlanId
  /** Count within the CURRENT 30-day period — resets to 0 when periodStart rolls over (see PLAN_LIMITS). Incremented before the flyers it counts are generated. */
  flyersCreated: number
  /** Epoch ms when the current 30-day usage period started. */
  periodStart: number
}

// ---- Deliverables / dashboard --------------------------------------------

export type FlyerStatus = "Pending" | "In Progress" | "Ready" | "Failed"
export type IntakeStatus = "Submitted" | "Not started"
export type BillingStatus = "Active" | "Past due" | "Trialing"

export interface FlyerDeliverable {
  id: string
  title: string
  status: FlyerStatus
  thumbnailUrl?: string
  downloadUrl?: string
  /** Set when status is "Failed" — shown to the client, with a retry option. */
  error?: string
}

export interface Deliverables {
  planId: PlanId
  planName: string
  billingStatus: BillingStatus
  intakeStatus: IntakeStatus
  flyers: FlyerDeliverable[]
  /** The latest submitter's real usage, for the dashboard's usage indicator. Null email = no intake yet. */
  email: string | null
  flyersCreated: number
  /** Always a real cap now — no plan is unlimited (see PLAN_LIMITS). */
  flyersLimit: number
  /** ISO timestamp when flyersCreated next resets to 0. */
  flyersResetAt: string
}

// ---- Form Fill (Pro-only) --------------------------------------------------
//
// A client uploads a fillable PDF form plus an information source (a file,
// a link, or both); the Form Fill Agent reads the form's real fields and
// the info source and returns a completed PDF. Pro-only — gated in
// /api/form-fill, not just hidden in the UI.

export type FormFillStatus = "Pending" | "In Progress" | "Ready" | "Failed"

export interface FormFillRequest {
  id: string
  /** The uploaded form's original filename, for display. */
  title: string
  status: FormFillStatus
  /** Set when status is "Ready" — a Blob URL to the completed PDF. */
  resultUrl?: string
  /** Set when status is "Failed". */
  error?: string
  /** Fields the agent couldn't confidently fill — surfaced even on an otherwise-successful fill. */
  unfilledNotes?: string[]
  createdAt: string
}

// A client's saved default info source for form-fill — the same shape
// form-fill already accepts per-request (a file and/or a link), just
// persisted so it doesn't need to be re-uploaded every time. Pro-only, same
// as form-fill itself.
export interface BusinessProfileRecord {
  savedAt: string
  link: string | null
  file: { blobUrl: string; mediaType: string; fileName: string } | null
}
