// ---------------------------------------------------------------------------
// OneFlyer shared data contracts
//
// These interfaces define the shapes exchanged between the marketing site,
// the client dashboard, and the EXTERNAL Claude-based agent pipeline (built
// outside of v0). Keep them stable so the pipeline can match up cleanly.
// ---------------------------------------------------------------------------

// The three real tiers — used BOTH for the marketing pricing page a visitor
// picks from AND as the real enforcement flag on a client's persisted
// record (see ClientRecord below). Picking a tier on the marketing page
// (via the onboarding ?plan= query string) is only ever a REQUEST — it does
// NOT by itself grant that plan. A client's real enforcement plan only ever
// changes via the admin route (POST /api/admin/set-plan), never inferred
// from an IntakeSubmission's planId — there's no real Stripe billing wired
// up yet, so trusting a client-selected value for enforcement would let
// anyone grant themselves Basic/Pro just by editing the URL.
export type PlanId = "trial" | "basic" | "pro"

// Real per-plan flyer caps — the single source of truth for both real
// enforcement (lib/store.ts, app/api/intake/route.ts) and marketing copy
// (lib/plans.ts), so the two can't drift out of sync the way the old
// marketing numbers did before this existed.
//
// These reset every 30 days from each client's own tracked period start
// (see ClientRecord.periodStart) — a real, enforced rolling window, not
// just a display label. Anchored to our own clock rather than a Stripe
// billing period since no real Stripe subscription exists yet; once it
// does, periodStart can be re-anchored to Stripe's current_period_start.
export const PLAN_LIMITS: Record<PlanId, number> = {
  trial: 3,
  basic: 25,
  pro: 50,
}

export interface Plan {
  id: PlanId
  name: string
  /** Short punchy positioning line under the name */
  tagline: string
  /** Small badge shown on the card, e.g. "Most Popular" */
  badge?: string
  /** Recurring monthly fee in whole dollars. 0 for the free trial tier. */
  monthlyFee: number
  description: string
  features: string[]
  /** A short callout reinforcing what this tier is for */
  note: string
  /** A short outcome-focused line reinforcing the result they get */
  outcome: string
  mostPopular?: boolean
  /** Placeholder Stripe price ID — wire this to a real price once a Stripe account exists. Unused for the free trial tier. */
  stripeMonthlyPriceId?: string
  ctaLabel: string
  /**
   * If set, the CTA renders as a plain link to this href instead of
   * triggering onSubscribe — for a tier with no real self-serve checkout
   * yet (e.g. a mailto: contact link). A button whose label promises an
   * upgrade but silently does nothing is worse than an honest "contact us."
   * Unused for all three current tiers — every button routes to onboarding.
   */
  ctaHref?: string
}

/** Shared reassurance line shown beneath all plans */
export const PLAN_GUARANTEE = "Cancel anytime · You own every flyer you generate"

/** Explains how the three tiers relate, shown beneath the pricing grid */
export const PLAN_EXPLAINER =
  "Every flyer is generated by our AI design engine and automatically brand-matched to your business — colors, fonts, and layout, no design skills required. Start with a free trial, then choose Basic or Pro as your business grows."

// ---- Intake / onboarding -------------------------------------------------

export type BrandStyle = "modern" | "classic" | "playful" | "minimal"

// Real segmentation tag, set once at signup (or once, later, via the
// dashboard banner for pre-existing accounts — see the note on
// ClientRecord.businessCategory below). Used to target templates/upsells/
// trial behavior at specific business types — most immediately, real
// estate/wholesaling via isRealEstate. A closed set (not free text) so
// downstream features can switch on it reliably instead of fuzzy-matching
// strings.
export const BUSINESS_CATEGORIES = [
  "Real Estate / Wholesaling",
  "Dental",
  "Gym/Fitness",
  "Contractor",
  "Restaurant/Cafe",
  "Other",
] as const

export type BusinessCategory = (typeof BUSINESS_CATEGORIES)[number]

export interface ServiceItem {
  id: string
  name: string
}

export interface IntakeSubmission {
  planId: PlanId | null
  /** Required — the onboarding UI blocks past its Category step until this is set (see components/onboarding-form.tsx). Set directly on the client's ClientRecord by /api/intake, never touched by the agent pipeline (same treatment as planId — see buildRawIntakePayload in lib/agent-pipeline/pipeline.ts). */
  businessCategory: BusinessCategory
  businessName: string
  industry: string
  yearsInBusiness: string
  services: ServiceItem[]
  logoFileName?: string
  brandColors?: string
  preferredStyle: BrandStyle
  voiceTone: string
  targetAudience: string
  contact: {
    email: string
    phone: string
    address: string
    website: string
    socialHandles: string
  }
  existingMaterialsFileName?: string
  /** Real Blob URLs — unlike logoFileName/existingMaterialsFileName, these are actually uploaded (see /api/onboarding/upload-photo), not just filenames. */
  flyerPhotoUrls?: string[]
  /** Explicit opt-in to AI-generated stock photos when a flyer has no client photo to use — Pro-only, real server-side gate (see hasProPhotoGeneration in lib/agent-pipeline/pipeline.ts). Never inferred from silence. */
  wantsAiPhotos?: boolean
  flyerNotes: string
  websitePreferences: string
  submittedAt?: string
}

// ---- Client records (usage limits) ---------------------------------------

// Persisted per-email record used for real enforcement of each plan's
// flyer limit (see PLAN_LIMITS). plan here is authoritative and only
// changes via the admin route — never inferred from an IntakeSubmission's
// planId (see the note on PlanId above).
export interface ClientRecord {
  email: string
  plan: PlanId
  /** Count within the CURRENT 30-day period — resets to 0 when periodStart rolls over (see PLAN_LIMITS). Incremented before the flyers it counts are generated. */
  flyersCreated: number
  /** Epoch ms when the current 30-day usage period started. */
  periodStart: number
  /** Set at signup (see IntakeSubmission.businessCategory) or, for accounts that predate this field, via the dashboard's one-time banner (POST /api/business-category). Always a real value — defaults to "Other" when nothing has been explicitly set yet (see getClient in lib/store.ts), never null/undefined, so downstream features can rely on it being present. */
  businessCategory: BusinessCategory
  /** Pure derivation of businessCategory === "Real Estate / Wholesaling" — recomputed wherever a ClientRecord is assembled (lib/store.ts) rather than stored separately, so it can never drift out of sync with businessCategory. */
  isRealEstate: boolean
}

// ---- Deliverables / dashboard --------------------------------------------

export type FlyerStatus = "Pending" | "In Progress" | "Ready" | "Failed"
export type IntakeStatus = "Submitted" | "Not started"
export type BillingStatus = "Active" | "Past due" | "Trialing"

// Same brand system, headline, offer, and CTA as the print flyer — just
// reformatted per channel. Set together with downloadUrl once a flyer is
// Ready; never partially populated.
export interface RepurposedFlyerContent {
  instagramDownloadUrl: string
  instagramCaption: string
  textBlurb: string
  nextdoorPost: string
}

export interface FlyerDeliverable {
  id: string
  title: string
  status: FlyerStatus
  thumbnailUrl?: string
  downloadUrl?: string
  repurposed?: RepurposedFlyerContent
  /** Short code embedded as a QR code on the flyer itself — used to fetch this flyer's scan/click stats (GET /api/tracking/[code]) and to render its public redeem page (/r/[code]). */
  trackingCode?: string
  /** Set when status is "Failed" — shown to the client, with a retry option. */
  error?: string
}

// ---- QR tracking ------------------------------------------------------------
//
// Every flyer gets a unique short code, embedded as a QR image ON the flyer
// itself (both print and Instagram variants), pointing at a hosted
// /r/[code] redeem page — not the business's own website, since a) not
// every client has one and b) a self-hosted page is the only way to
// actually count a scan. Two counters, not one: "scans" (the redeem page
// loading) and "clicks" (someone tapping the actual CTA on that page) —
// scans alone can't distinguish "glanced at it" from "took the action."

export interface TrackingRecord {
  email: string
  flyerId: string
  businessName: string
  /** Populated once the Flyer Agent responds — null in the brief window between QR generation (before the agent call) and the flyer being marked Ready. */
  headline: string | null
  offer: string | null
  cta: string | null
  disclaimer: string | null
  phone: string
  website: string | null
  createdAt: string
}

export interface TrackingStats {
  scans: number
  clicks: number
}

export interface Deliverables {
  planId: PlanId
  planName: string
  billingStatus: BillingStatus
  intakeStatus: IntakeStatus
  flyers: FlyerDeliverable[]
  /** The latest submitter's real usage, for the dashboard's usage indicator. Null email = no intake yet. */
  email: string | null
  flyersCreated: number
  /** Always a real cap now — no plan is unlimited (see PLAN_LIMITS). */
  flyersLimit: number
  /** ISO timestamp when flyersCreated next resets to 0. */
  flyersResetAt: string
  printRequests: PrintRequest[]
  /** See ClientRecord.businessCategory — defaults to "Other" until explicitly set. */
  businessCategory: BusinessCategory
  isRealEstate: boolean
  /** True only when this client has never explicitly set a category (an account that predates this field) — drives the dashboard's one-time, non-blocking banner (see DashboardClient). False the moment they've set any category, including explicitly choosing "Other". */
  businessCategoryIsDefaulted: boolean
}

// ---- Print fulfillment ------------------------------------------------------
//
// A client requests printed copies of one of their own Ready flyers —
// quantity + shipping address. Deliberately NOT a real order: there's no
// Stripe billing yet, so nothing here calls a print API or charges anyone.
// It's a queue the admin sees and fulfills/invoices manually outside the
// app. Basic+/Pro — Trial doesn't include it (enforced in
// /api/print-requests, not just hidden in the UI).

export type PrintRequestStatus = "Requested" | "Fulfilled" | "Cancelled"

export interface PrintRequest {
  id: string
  flyerId: string
  flyerTitle: string
  quantity: number
  shippingName: string
  shippingAddress: string
  notes: string | null
  status: PrintRequestStatus
  createdAt: string
}

// ---- Form Fill (Pro-only) --------------------------------------------------
//
// A client uploads a fillable PDF form plus an information source (a file,
// a link, or both); the Form Fill Agent reads the form's real fields and
// the info source and returns a completed PDF. Pro-only — gated in
// /api/form-fill, not just hidden in the UI.

export type FormFillStatus = "Pending" | "In Progress" | "Ready" | "Failed"

export interface FormFillRequest {
  id: string
  /** The uploaded form's original filename, for display. */
  title: string
  status: FormFillStatus
  /** Set when status is "Ready" — a Blob URL to the completed PDF. */
  resultUrl?: string
  /** Set when status is "Failed". */
  error?: string
  /** Fields the agent couldn't confidently fill — surfaced even on an otherwise-successful fill. */
  unfilledNotes?: string[]
  createdAt: string
}

// A client's saved default info source for form-fill — the same shape
// form-fill already accepts per-request (a file and/or a link), just
// persisted so it doesn't need to be re-uploaded every time. Pro-only, same
// as form-fill itself.
export interface BusinessProfileRecord {
  savedAt: string
  link: string | null
  file: { blobUrl: string; mediaType: string; fileName: string } | null
}

// ---- AI generation cost log -------------------------------------------------
//
// One row per real Claude API call in the Intake/Brand/Flyer pipeline — NOT
// one row per flyer. A single Flyer Agent call can produce several flyers
// in one batch, so flyerId is null whenever an entry doesn't map to exactly
// one flyer (a batch of more than one, or the Intake/Brand stages, which
// each run once per submission before any flyer id exists yet). email is
// this app's real per-account identity (see ClientRecord) — there's no
// separate "business" entity distinct from the account itself, so there's
// no businessId field here.

export type GenerationAgentType = "intake" | "brand" | "flyer"

export interface GenerationLogEntry {
  id: string
  email: string
  flyerId: string | null
  agentType: GenerationAgentType
  model: string
  inputTokens: number
  outputTokens: number
  estimatedCostUsd: number
  createdAt: string
}
